using System;
using System.Collections.Generic;
using System.Text;

namespace AssetForge.Core.Contracts
{
    /// <summary>
    /// Notification of the progress of a job. From worker to editor.
    /// </summary>
    public sealed record JobProgress
    {
        public required Guid JobId { get; init; }
        public required JobState State { get; init; }
        public required double Percent {  get; init; }

        public string? WorkerId { get; init; }
        public string? Message { get; init; }
    }

    /// <summary>
    /// Result of a job.
    /// </summary>
    public sealed record JobResult
    {
        public required Guid JobId { get; init; }
        public required JobState State { get; init; }
        public string? OutputPath { get; init; }
        public int MipLevels { get; init; }
        public long ElapsedMs { get; init; }
        /// <summary>
        /// Indicates whether the result was retrieved from cache or generated by processing.
        /// </summary>
        public bool FromCache { get; init; }
        public string? Error { get; init; }
    }
}
